In [1]:
'''
# 📓 Feature Engineering

## 🎯 Objective

The objective of this notebook is to create new features from the cleaned and merged e-commerce dataset. These engineered features enhance the dataset by extracting meaningful business information, making it more suitable for advanced analytics, SQL analysis, machine learning models, and business intelligence dashboards.

The newly created features will help identify customer purchasing patterns, delivery performance, revenue distribution, and time-based trends while improving the predictive capability of future machine learning models.
'''

'\n# 📓 Feature Engineering\n\n## 🎯 Objective\n\nThe objective of this notebook is to create new features from the cleaned and merged e-commerce dataset. These engineered features enhance the dataset by extracting meaningful business information, making it more suitable for advanced analytics, SQL analysis, machine learning models, and business intelligence dashboards.\n\nThe newly created features will help identify customer purchasing patterns, delivery performance, revenue distribution, and time-based trends while improving the predictive capability of future machine learning models.\n'

In [2]:
# ==========================================================
# Import Required Libraries
# ==========================================================

import pandas as pd
import numpy as np

# Display all columns
pd.set_option('display.max_columns', None)

In [5]:
# ==========================================================
# Load the Merged Dataset
# ==========================================================

df = pd.read_csv("../data/processed/olist_master_dataset.csv")

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [6]:
# Shape of Dataset

print("Shape of Dataset:", df.shape)

Shape of Dataset: (119143, 36)

In [7]:
# First Five Rows

df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,No Title,No Comment,2018-08-18 00:00:00,2018-08-22 19:07:58

In [8]:
# Dataset Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 36 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  object
 4   order_approved_at              118966 non-null  object
 5   order_delivered_carrier_date   117057 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  119143 non-null  object
 8   customer_unique_id             119143 non-null  object
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  object
 11  customer_state                 119143 non-null  object
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  object
 14  seller_id                      118310 non-null  object
 15  shipping_limit_date            118310 non-null  object
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  product_category_name          118310 non-null  object
 19  product_name_lenght            118310 non-null  float64
 20  product_description_lenght     118310 non-null  float64
 21  product_photos_qty             118310 non-null  float64
 22  product_weight_g               118310 non-null  float64
 23  product_length_cm              118310 non-null  float64
 24  product_height_cm              118310 non-null  float64
 25  product_width_cm               118310 non-null  float64
 26  payment_sequential             119140 non-null  float64
 27  payment_type                   119140 non-null  object
 28  payment_installments           119140 non-null  float64
 29  payment_value                  119140 non-null  float64
 30  review_id                      118146 non-null  object
 31  review_score                   118146 non-null  float64
 32  review_comment_title           118146 non-null  object
 33  review_comment_message         118146 non-null  object
 34  review_creation_date           118146 non-null  object
 35  review_answer_timestamp        118146 non-null  object
dtypes: float64(14), int64(1), object(21)
memory usage: 32.7+ MB

In [9]:
# Check Missing Values

df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 177
order_delivered_carrier_date     2086
order_delivered_customer_date    3421
order_estimated_delivery_date       0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
order_item_id                     833
product_id                        833
seller_id                         833
shipping_limit_date               833
price                             833
freight_value                     833
product_category_name             833
product_name_lenght               833
product_description_lenght        833
product_photos_qty                833
product_weight_g                  833
product_length_cm                 833
product_height_cm                 833
product_width_cm                  833
payment_sequential                  3
payment_type                        3
payment_installments                3
payment_value                       3
review_id                         997
review_score                      997
review_comment_title              997
review_comment_message            997
review_creation_date              997
review_answer_timestamp           997
dtype: int64

In [10]:
df.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state',
 'order_item_id',
 'product_id',
 'seller_id',
 'shipping_limit_date',
 'price',
 'freight_value',
 'product_category_name',
 'product_name_lenght',
 'product_description_lenght',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm',
 'payment_sequential',
 'payment_type',
 'payment_installments',
 'payment_value',
 'review_id',
 'review_score',
 'review_comment_title',
 'review_comment_message',
 'review_creation_date',
 'review_answer_timestamp']

In [11]:
'''
## 1. Convert Date Columns

Before creating time-based features, all date-related columns must be converted to the datetime format. This enables date calculations such as delivery duration, purchase month, purchase year, and order approval time.
'''

'\n## 1. Convert Date Columns\n\nBefore creating time-based features, all date-related columns must be converted to the datetime format. This enables date calculations such as delivery duration, purchase month, purchase year, and order approval time.\n'

In [12]:
# ==========================================================
# Convert Date Columns
# ==========================================================

date_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
    'shipping_limit_date',
    'review_creation_date',
    'review_answer_timestamp'
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col])

print("Date columns converted successfully!")

Date columns converted successfully!

In [13]:
'''
## 2. Date & Time Features

Time-based features help analyze customer purchasing behavior across different months, weekdays, quarters, and hours. These features are valuable for identifying seasonal trends, peak shopping periods, and customer activity patterns.
'''

'\n## 2. Date & Time Features\n\nTime-based features help analyze customer purchasing behavior across different months, weekdays, quarters, and hours. These features are valuable for identifying seasonal trends, peak shopping periods, and customer activity patterns.\n'

In [14]:
# ==========================================================
# Date & Time Features
# ==========================================================

df['purchase_year'] = df['order_purchase_timestamp'].dt.year

df['purchase_month'] = df['order_purchase_timestamp'].dt.month

df['purchase_day'] = df['order_purchase_timestamp'].dt.day

df['purchase_day_name'] = df['order_purchase_timestamp'].dt.day_name()

df['purchase_hour'] = df['order_purchase_timestamp'].dt.hour

df['purchase_quarter'] = df['order_purchase_timestamp'].dt.quarter

df['is_weekend'] = df['purchase_day_name'].isin(['Saturday', 'Sunday'])

In [15]:
df[['purchase_year',
    'purchase_month',
    'purchase_day',
    'purchase_day_name',
    'purchase_hour',
    'purchase_quarter',
    'is_weekend']].head()

,purchase_year,purchase_month,purchase_day,purchase_day_name,purchase_hour,purchase_quarter,is_weekend
0,2017,10,2,Monday,10,4,False
1,2017,10,2,Monday,10,4,False
2,2017,10,2,Monday,10,4,False
3,2018,7,24,Tuesday,20,3,False
4,2018,8,8,Wednesday,8,3,False

In [16]:
'''
## 3. Delivery Features

Delivery-related features provide insights into the efficiency of the order fulfillment process. By calculating delivery durations and comparing actual delivery dates with estimated delivery dates, we can identify delays, measure logistics performance, and evaluate customer experience.

These engineered features will support future business analysis, SQL queries, and predictive machine learning models.
'''

'\n## 3. Delivery Features\n\nDelivery-related features provide insights into the efficiency of the order fulfillment process. By calculating delivery durations and comparing actual delivery dates with estimated delivery dates, we can identify delays, measure logistics performance, and evaluate customer experience.\n\nThese engineered features will support future business analysis, SQL queries, and predictive machine learning models.\n'

In [17]:
# ==========================================================
# Delivery Days
# ==========================================================

df['delivery_days'] = (
    df['order_delivered_customer_date']
    - df['order_purchase_timestamp']
).dt.days

In [18]:
# ==========================================================
# Approval Days
# ==========================================================

df['approval_days'] = (
    df['order_approved_at']
    - df['order_purchase_timestamp']
).dt.days

In [19]:
# ==========================================================
# Estimated Delivery Gap
# ==========================================================

df['estimated_delivery_gap'] = (
    df['order_estimated_delivery_date']
    - df['order_delivered_customer_date']
).dt.days

In [20]:
# ==========================================================
# Late Delivery Flag
# ==========================================================

df['late_delivery'] = (
    df['order_delivered_customer_date']
    > df['order_estimated_delivery_date']
)

In [21]:
df[
    [
        'delivery_days',
        'approval_days',
        'estimated_delivery_gap',
        'late_delivery'
    ]
].head()

   delivery_days  approval_days  estimated_delivery_gap  late_delivery
0            8.0            0.0                     7.0          False
1            8.0            0.0                     7.0          False
2            8.0            0.0                     7.0          False
3           13.0            1.0                     5.0          False
4            9.0            0.0                    17.0          False

In [22]:
df[
    [
        'delivery_days',
        'approval_days',
        'estimated_delivery_gap'
    ]
].describe()

       delivery_days  approval_days  estimated_delivery_gap
count  115722.000000  118966.000000           115722.000000
mean       12.022589       0.274465               11.048392
std         9.454922       0.980584               10.163801
min         0.000000       0.000000             -189.000000
25%         6.000000       0.000000                6.000000
50%        10.000000       0.000000               12.000000
75%        15.000000       0.000000               16.000000
max       209.000000     187.000000              146.000000

In [23]:
'''
## 4. Revenue & Order Features

Revenue-based features help measure the financial value of each order and categorize orders based on their monetary contribution. These engineered features are useful for identifying high-value customers, analyzing purchasing behavior, and supporting future predictive models.

The features created in this section will help answer business questions such as:
- Which orders generate the highest revenue?
- How many high-value orders are placed?
- What is the distribution of order values?
'''

'\n## 4. Revenue & Order Features\n\nRevenue-based features help measure the financial value of each order and categorize orders based on their monetary contribution. These engineered features are useful for identifying high-value customers, analyzing purchasing behavior, and supporting future predictive models.\n\nThe features created in this section will help answer business questions such as:\n- Which orders generate the highest revenue?\n- How many high-value orders are placed?\n- What is the distribution of order values?\n'

In [24]:
# ==========================================================
# Total Order Value
# ==========================================================

df['total_order_value'] = df['price'] + df['freight_value']

In [25]:
# ==========================================================
# High Value Order
# ==========================================================

average_order_value = df['total_order_value'].mean()

df['high_value_order'] = (
    df['total_order_value'] > average_order_value
)

In [26]:
# ==========================================================
# Revenue Bucket
# ==========================================================

df['revenue_bucket'] = pd.qcut(
    df['total_order_value'],
    q=3,
    labels=['Low', 'Medium', 'High']
)

In [27]:
df[
    [
        'price',
        'freight_value',
        'total_order_value',
        'high_value_order',
        'revenue_bucket'
    ]
].head()

    price  freight_value  total_order_value  high_value_order revenue_bucket
0   29.99           8.72              38.71             False            Low
1   29.99           8.72              38.71             False            Low
2   29.99           8.72              38.71             False            Low
3  118.70          22.76             141.46              True           High
4  159.90          19.22             179.12              True           High

In [28]:
print(df['high_value_order'].value_counts())

print()

print(df['revenue_bucket'].value_counts())

high_value_order
False    84090
True     35053
Name: count, dtype: int64

revenue_bucket
Medium    39442
Low       39438
High      39430
Name: count, dtype: int64

In [29]:
df['order_id'].nunique(), len(df)

(99441, 119143)

In [30]:
# ==========================================================
# Actual Order Value
# ==========================================================

df['order_value'] = df.groupby('order_id')['total_order_value'].transform('sum')

In [31]:
average_order_value = df['order_value'].mean()

df['high_value_order'] = df['order_value'] > average_order_value

In [32]:
df['revenue_bucket'] = pd.qcut(
    df['order_value'],
    q=3,
    labels=['Low', 'Medium', 'High']
)

In [33]:
# Display Revenue Features

df[
    [
        'price',
        'freight_value',
        'total_order_value',
        'order_value',
        'high_value_order',
        'revenue_bucket'
    ]
].head()

,price,freight_value,total_order_value,order_value,high_value_order,revenue_bucket
0,29.99,8.72,38.71,116.13,False,Medium
1,29.99,8.72,38.71,116.13,False,Medium
2,29.99,8.72,38.71,116.13,False,Medium
3,118.70,22.76,141.46,141.46,False,Medium
4,159.90,19.22,179.12,179.12,False,High

In [34]:
# High Value Orders

print(df['high_value_order'].value_counts())

print("\nRevenue Bucket Distribution\n")

print(df['revenue_bucket'].value_counts())

high_value_order
False    90148
True     28995
Name: count, dtype: int64

Revenue Bucket Distribution

revenue_bucket
Medium    39719
Low       39715
High      39709
Name: count, dtype: int64

In [35]:
df[['order_value']].describe()

         order_value
count  119143.000000
mean      216.025218
std       469.002575
min         0.000000
25%        67.600000
50%       120.030000
75%       212.585000
max     13664.080000

In [36]:
'''
## 5. Customer Features

Customer-based feature engineering helps understand customer purchasing behavior and loyalty. These features provide insights into how frequently customers place orders, how much they spend over time, and whether they are repeat buyers.

These features are valuable for customer segmentation, retention analysis, SQL reporting, and predictive machine learning models.
'''

'\n## 5. Customer Features\n\nCustomer-based feature engineering helps understand customer purchasing behavior and loyalty. These features provide insights into how frequently customers place orders, how much they spend over time, and whether they are repeat buyers.\n\nThese features are valuable for customer segmentation, retention analysis, SQL reporting, and predictive machine learning models.\n'

In [37]:
# ==========================================================
# Customer Order Count
# ==========================================================

df['customer_order_count'] = (
    df.groupby('customer_unique_id')['order_id']
      .transform('nunique')
)

In [38]:
# ==========================================================
# Repeat Customer Flag
# ==========================================================

df['repeat_customer'] = (
    df['customer_order_count'] > 1
)

In [39]:
# ==========================================================
# Customer Total Spending
# ==========================================================

df['customer_total_spending'] = (
    df.groupby('customer_unique_id')['order_value']
      .transform('sum')
)

In [40]:
# ==========================================================
# Average Order Value Per Customer
# ==========================================================

df['average_order_value_per_customer'] = (
    df['customer_total_spending']
    / df['customer_order_count']
)

In [41]:
df[
    [
        'customer_unique_id',
        'customer_order_count',
        'repeat_customer',
        'customer_total_spending',
        'average_order_value_per_customer'
    ]
].head()

,customer_unique_id,customer_order_count,repeat_customer,customer_total_spending,average_order_value_per_customer
0,7c396fd4830fd04220f754e42b4e5bff,2,True,392.50,196.25
1,7c396fd4830fd04220f754e42b4e5bff,2,True,392.50,196.25
2,7c396fd4830fd04220f754e42b4e5bff,2,True,392.50,196.25
3,af07308b275d755c9edb36a90c618231,1,False,141.46,141.46
4,3a653a41f6f9fc3d2a113cf8398680e8,1,False,179.12,179.12

In [42]:
print(df['repeat_customer'].value_counts())

print("\nCustomer Feature Statistics:\n")

df[
    [
        'customer_order_count',
        'customer_total_spending',
        'average_order_value_per_customer'
    ]
].describe()

repeat_customer
False    110404
True       8739
Name: count, dtype: int64

Customer Feature Statistics:

,customer_order_count,customer_total_spending,average_order_value_per_customer
count,119143.000000,119143.000000,119143.000000
mean,1.091126,1031.473286,887.433452
std,0.410960,10315.336158,8839.276965
min,1.000000,0.000000,0.000000
25%,1.000000,73.340000,71.780000
50%,1.000000,146.340000,139.180000
75%,1.000000,340.600000,311.595000
max,17.000000,385169.590000,385169.590000

In [43]:
'''
## 6. Payment Features

Payment-related feature engineering helps categorize customer payment behavior. Instead of using raw installment numbers, grouping them into meaningful categories makes analysis easier and provides useful features for business reporting and predictive models.

These features can help answer questions such as:
- Do customers prefer single payments or installments?
- Which installment groups contribute more revenue?
- Does installment behavior affect customer spending?
'''

'\n## 6. Payment Features\n\nPayment-related feature engineering helps categorize customer payment behavior. Instead of using raw installment numbers, grouping them into meaningful categories makes analysis easier and provides useful features for business reporting and predictive models.\n\nThese features can help answer questions such as:\n- Do customers prefer single payments or installments?\n- Which installment groups contribute more revenue?\n- Does installment behavior affect customer spending?\n'

In [44]:
# ==========================================================
# Installment Category
# ==========================================================

df['installment_category'] = pd.cut(
    df['payment_installments'],
    bins=[0, 1, 3, 6, 24],
    labels=[
        'Single Payment',
        'Short Installment',
        'Medium Installment',
        'Long Installment'
    ]
)

In [45]:
df[
    [
        'payment_installments',
        'installment_category'
    ]
].head(10)

   payment_installments installment_category
0                   1.0       Single Payment
1                   1.0       Single Payment
2                   1.0       Single Payment
3                   1.0       Single Payment
4                   3.0    Short Installment
5                   1.0       Single Payment
6                   1.0       Single Payment
7                   6.0   Medium Installment
8                   1.0       Single Payment
9                   3.0    Short Installment

In [46]:
df['installment_category'].value_counts()

installment_category
Single Payment        59446
Short Installment     25727
Medium Installment    18843
Long Installment      15121
Name: count, dtype: int64

In [47]:
print("Dataset Shape:", df.shape)

Dataset Shape: (119143, 56)

In [48]:
df.isnull().sum()

order_id                               0
customer_id                            0
order_status                           0
order_purchase_timestamp               0
order_approved_at                    177
order_delivered_carrier_date        2086
order_delivered_customer_date       3421
order_estimated_delivery_date          0
customer_unique_id                     0
customer_zip_code_prefix               0
customer_city                          0
customer_state                         0
order_item_id                        833
product_id                           833
seller_id                            833
shipping_limit_date                  833
price                                833
freight_value                        833
product_category_name                833
product_name_lenght                  833
product_description_lenght           833
product_photos_qty                   833
product_weight_g                     833
product_length_cm                    833
product_height_cm                    833
product_width_cm                     833
payment_sequential                     3
payment_type                           3
payment_installments                   3
payment_value                          3
review_id                            997
review_score                         997
review_comment_title                 997
review_comment_message               997
review_creation_date                 997
review_answer_timestamp              997
purchase_year                          0
purchase_month                         0
purchase_day                           0
purchase_day_name                      0
purchase_hour                          0
purchase_quarter                       0
is_weekend                             0
delivery_days                       3421
approval_days                        177
estimated_delivery_gap              3421
late_delivery                          0
total_order_value                    833
high_value_order                       0
revenue_bucket                         0
order_value                            0
customer_order_count                   0
repeat_customer                        0
customer_total_spending                0
average_order_value_per_customer       0
installment_category                   6
dtype: int64

In [49]:
new_features = [
    'purchase_year',
    'purchase_month',
    'purchase_day',
    'purchase_day_name',
    'purchase_hour',
    'purchase_quarter',
    'is_weekend',
    'delivery_days',
    'approval_days',
    'estimated_delivery_gap',
    'late_delivery',
    'total_order_value',
    'order_value',
    'high_value_order',
    'revenue_bucket',
    'customer_order_count',
    'repeat_customer',
    'customer_total_spending',
    'average_order_value_per_customer',
    'installment_category'
]

df[new_features].head()

,purchase_year,purchase_month,purchase_day,purchase_day_name,purchase_hour,purchase_quarter,is_weekend,delivery_days,approval_days,estimated_delivery_gap,late_delivery,total_order_value,order_value,high_value_order,revenue_bucket,customer_order_count,repeat_customer,customer_total_spending,average_order_value_per_customer,installment_category
0,2017,10,2,Monday,10,4,False,8.0,0.0,7.0,False,38.71,116.13,False,Medium,2,True,392.50,196.25,Single Payment
1,2017,10,2,Monday,10,4,False,8.0,0.0,7.0,False,38.71,116.13,False,Medium,2,True,392.50,196.25,Single Payment
2,2017,10,2,Monday,10,4,False,8.0,0.0,7.0,False,38.71,116.13,False,Medium,2,True,392.50,196.25,Single Payment
3,2018,7,24,Tuesday,20,3,False,13.0,1.0,5.0,False,141.46,141.46,False,Medium,1,False,141.46,141.46,Single Payment
4,2018,8,8,Wednesday,8,3,False,9.0,0.0,17.0,False,179.12,179.12,False,High,1,False,179.12,179.12,Short Installment

In [50]:
# ==========================================================
# Save Engineered Dataset
# ==========================================================

df.to_csv(
    "../data/processed/engineered_data.csv",
    index=False
)

print("✅ Engineered dataset saved successfully!")

✅ Engineered dataset saved successfully!

In [51]:
'''
## Summary

In this notebook, we transformed the cleaned and merged dataset into a feature-rich analytical dataset by engineering meaningful business features.

### Features Created

- Date & Time Features
- Delivery Features
- Revenue Features
- Customer Features
- Payment Features

The engineered dataset is now ready for SQL analysis, advanced business analytics, and machine learning.

The next notebook will focus on answering business questions using SQL queries on this engineered dataset.
'''

'\n## Summary\n\nIn this notebook, we transformed the cleaned and merged dataset into a feature-rich analytical dataset by engineering meaningful business features.\n\n### Features Created\n\n- Date & Time Features\n- Delivery Features\n- Revenue Features\n- Customer Features\n- Payment Features\n\nThe engineered dataset is now ready for SQL analysis, advanced business analytics, and machine learning.\n\nThe next notebook will focus on answering business questions using SQL queries on this engineered dataset.\n'